<a href="https://colab.research.google.com/github/frankodzia/ai-course-gp/blob/main/lesson_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print("Array:")
print(array)
print(f"Shape of array: {np.shape(array)}")


array2x6 = array.reshape(2, 6)

print("Array 2x6:")
print(array2x6)
print(f"Shape of array: {array2x6.shape}")


Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of array: (12,)
Array 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape of array: (2, 6)


In [ ]:
import numpy as np

usorted1D = np.array([3, 6, 2, 4])
sorted1D = np.sort(usorted1D)
print(f"Sorted 1D: {sorted1D}")

unsorted2D = np.array([
    [7, 2, 9],
    [4, 8, 1],
    [5, 6, 3]
])

sorted2D_axis0 = np.sort(unsorted2D, axis=0)
print(f"Sorted array by axis 0:\n{sorted2D_axis0}\n")

sorted2D_axis1 = np.sort(unsorted2D, axis=1)
print(f"Sorted array by axis 1:\n{sorted2D_axis1}")

players_data = np.array([
("Faker", "T1", 5),
("TheShy", "Weibo Gaming", 1),
("Uzi", "Emerytowany", 0),
("Ruler", "JD Gaming", 1),
("Doinb", "Emerytowany", 1),
("Rekkles", "Los Ratones", 1),
("Caps", "G2 Esports", 0)
], dtype= [('Nick', 'U30'), ('Team', 'U30'), ('Worlds Title Count', 'i4')])

print("sortowanie po liczbie tytułów: ")
print(np.flip(players_data,order = 'Worlds Title Count'))


Sorted 1D: [2 3 4 6]
Sorted array by axis 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]

Sorted array by axis 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]


In [ ]:
#losowanie

from numpy import random

print(f"Lsowanie 10 liczb z przedziału od 10 do 121")

for i in range(10):
  print(random.randint(10,121))

#losowanie z listy
daty = [1241, 972, 1605, 1444, 1683]

print(f"Losowanie data ze zbioru: {random.choice(daty)}")
print(f"Losowanie 3 daty ze zbioru: {random.choice(daty, 3)}")

random.shuffle(daty)
print(f"przetasowane daty: {daty}")

Lsowanie 10 liczb z przedziału od 10 do 121
63
68
12
12
40
104
112
16
91
13
Losowanie data ze zbioru: 1241
Losowanie 3 daty ze zbioru: [ 972 1241 1683]
przetasowane daty: [1241, 1444, 1683, 1605, 972]


In [ ]:
import numpy as np

array1D = np.array([1,2,3,4,5])
print(array1D[2:5])


[3 4 5]


In [ ]:
#iterowanie po elementach

import numpy as np

array2D = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])

for i in array2D:
  for j in i:
    print(j)

    for i in np.nditer(array2D):
      print(i)

1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
2
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
3
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
4
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
5
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
6
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
7
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
8
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
9
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
10
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
11
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
12
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
13
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
14
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [1]:
import numpy as np

array2D = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])

index6 = np.where(array2D == 6)
print(index6)

(array([1]), array([0]))
